# AppVeyor CI build file

# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

image: Visual Studio 2017

# version format
version: 4.1.{build}

shallow_clone: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

configuration: Release

build_script:
- ps: .\Build.ps1 -Configuration Release

after_build:
- ps: .\Pack.ps1 -Configuration Release -Version $env:APPVEYOR_BUILD_VERSION

artifacts:
- path: artifacts\**\CertiPay.Common.*.nupkg

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test:
  categories:
    except:
      - Integration
  assemblies:
    - '**\bin\$(Configuration)\**\CertiPay.Common.Tests.dll'

#---------------------------------#
#       artifacts configuration   #
#---------------------------------#

deploy:
- provider: NuGet
  on: 
    branch: master
  api_key:
    secure: oy2iupdor73a2t2l4hnasxnjdb7nmmlunfamwe77lddb3q